config/routes.rb
Learnstat::Application.routes.draw do
  resources :users
  resource :user_session
  resource :account

  match "/signup" => "users#new"
  match "/login"  => "user_sessions#create"
  match "/logout" => "user_sessions#destroy"

  resources :courses do
    resources :quizzes, :only => [:index, :new, :create]
    resources :announcements
    resources :documents
    resources :exams, :only => [:new, :create]

    resource :gradebook
    resource :roster
    resource :bonus_points
  end

  resources :exams, :only => [:show, :edit, :update]

  resources :quizzes, :except => [:new, :create] do
    resources :questions, :controller => "QuizQuestions", :only => [:new, :create]
    resources :responses, :controller => "QuizResponses", :only => [:create]
  end

  resources :quiz_questions, :except => [:new, :create]

  resources :questions do
    resources :choices, :controller => "QuestionChoices"
  end

  root :to => "courses#index"
end

app/models/question_choice.rb
class QuestionChoice < ActiveRecord::Base

  belongs_to :question

  validates_presence_of :content

  def to_s
    content
  end

end

app/controllers/question_choices_controller.rb
class QuestionChoicesController < ApplicationController

  before_filter :require_instructor

  inherit_resources
  defaults :collection_name => "choices"
  belongs_to :question, :optional => true
  actions :all, :except => :index

  def create
    create! { @question }
  end

  def update
    update! { @question }
  end

  def destroy
    destroy! { @question }
  end

end

app/helpers/question_choices_helper.rb
module QuestionChoicesHelper
end

app/views/question_choices/_form.html.haml
= form.input :content

app/views/question_choices/_question_choice.html.haml
%li= question_choice.content.html_safe

app/views/question_choices/edit.html.haml
%h2 Edit question choice

= simple_form_for @question_choice, :url => question_choice_path(@question, @question_choice) do |form|
  = render "form", :form => form
  %p
    = form.submit "Update"
    = link_to "Back", root_path

app/views/question_choices/new.html.haml
%h2 New question choice

= simple_form_for @question_choice, :url => question_choices_path(@question) do |form|
  = render "form", :form => form
  %p
    = form.submit "Create"
    = link_to "Back", root_path