config/routes.rb
Learnstat::Application.routes.draw do
  resources :users
  resource :user_session
  resource :account

  match "/signup" => "users#new"
  match "/login"  => "user_sessions#create"
  match "/logout" => "user_sessions#destroy"

  resources :courses do
    resources :quizzes, :only => [:index, :new, :create]
    resources :announcements
    resources :documents
    resources :exams, :only => [:new, :create]

    resource :gradebook
    resource :roster
    resource :bonus_points
  end

  resources :exams, :only => [:show, :edit, :update]

  resources :quizzes, :except => [:new, :create] do
    resources :questions, :controller => "QuizQuestions", :only => [:new, :create]
    resources :responses, :controller => "QuizResponses", :only => [:create]
  end

  resources :quiz_questions, :except => [:new, :create]

  resources :questions do
    resources :choices, :controller => "QuestionChoices"
  end

  root :to => "courses#index"
end

app/models/exam.rb
class Exam < ActiveRecord::Base

  belongs_to :course

  has_many :grades

  accepts_nested_attributes_for :grades

  def grade_for user
    if (grade = grades.find_by_user_id(user.id))
      grade.value
    else
      '**'
    end
  end

  def mean
    return nil unless grades.size > 0
    @mean ||= grades.sum(:value) / grades.size.to_f
  end

  def standard_deviation
    return nil unless grades.size > 1
    (grades.map {|grade| (grade.value - mean) ** 2 }.sum / (grades.size - 1)) ** 0.5
  end

end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController

  before_filter :require_instructor, :except => :show

  inherit_resources
  belongs_to :course, :optional => true
  actions :all, :except => :index

  def create
    create! { course_gradebook_path(@exam.course) }
  end

  def update
    update! { course_gradebook_path(@exam.course) }
  end

end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.haml
%p= form.input :name
%p= form.input :given_on, :as => :date
%p= form.input :final, :as => :boolean

%table
  %tr
    %th Name
    %th Grade

  - @exam.course.students.each do |student|
    = form.fields_for :grades, @exam.grades.build(:user => student) do |grade_form|
      %tr
        %td= student
        %td
          = grade_form.hidden_field :user_id, :value => student.id
          = grade_form.text_field :value, :size => 4

app/views/exams/edit.html.haml
%h2 Edit an Exam

= simple_form_for [@course, @exam] do |form|
  = render "form", :form => form

  %p
    = form.submit "Update"
    = link_to 'Cancel', @course

app/views/exams/new.html.haml
%h2 Add an Exam

= simple_form_for [@course, @exam] do |form|
  = render "form", :form => form

  %p
    = form.submit "Create"
    = link_to 'Cancel', @course

app/views/exams/show.html.haml
%h2= @exam.name

%p
  %label{:for => "mean"} Mean Score:
  = percent_format @exam.mean

%p
  %label{:for => "sd"} Standard Deviation:
  = number_with_precision @exam.standard_deviation, :precision => 2

%p= instructor_link "Edit exam", "application_form_edit.png", edit_exam_path(@exam)
%p= link_to "Back", course_path(@exam.course)