config/routes.rb
Learnstat::Application.routes.draw do
  resources :users
  resource :user_session
  resource :account

  match "/signup" => "users#new"
  match "/login"  => "user_sessions#create"
  match "/logout" => "user_sessions#destroy"

  resources :courses do
    resources :quizzes, :only => [:index, :new, :create]
    resources :announcements
    resources :documents
    resources :exams, :only => [:new, :create]

    resource :gradebook
    resource :roster
    resource :bonus_points
  end

  resources :exams, :only => [:show, :edit, :update]

  resources :quizzes, :except => [:new, :create] do
    resources :questions, :controller => "QuizQuestions", :only => [:new, :create]
    resources :responses, :controller => "QuizResponses", :only => [:create]
  end

  resources :quiz_questions, :except => [:new, :create]

  resources :questions do
    resources :choices, :controller => "QuestionChoices"
  end

  root :to => "courses#index"
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_filter :require_user

  inherit_resources
  defaults :instance_name => "user"
  actions :show, :edit, :update

  def update
    update! { account_path }
  end

  protected

  def resource
    @user ||= current_user
    @course = @user.course
    @user
  end

end

app/views/accounts/edit.html.haml
= simple_form_for @user, :url => account_path do |form|
  = form.input :first_name
  = form.input :last_name
  = form.input :password
  = form.input :password_confirmation

  %p
    = form.submit "Update", :class => "button"
    = link_to "Cancel", root_path, :class => "button"

app/views/accounts/show.html.haml
%h2 My Profile

%p
  %label Email:
  = @user.email

%p
  %label First name:
  = @user.first_name

%p
  %label Last name:
  = @user.last_name

%p= link_to "Edit My Profile", edit_account_path